name: flutterwind
description: Style your Flutter widgets like Tailwind CSS.
homepage: https://flutterwind.vercel.app/
repository: https://github.com/MRGRAVITY817/flutterwind
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.6

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  flutter_test:
      sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  generate: true
  uses-material-design: true
